### PR TITLE
[ refactor ] use interface similar to Show

### PR DESCRIPTION
**Pull request by stefan-hoeck**
I did not want to include this change in the big performance refactoring, because I'm not sure this redesign of the `Pretty` interface is the way to go. It does make deriving of `Pretty` implementations simpler, though. With this change, `Pretty` is in the spirit of `Show`, with a `prettyPrec : Prec -> a -> Doc opts` function. Unlike with `Show`, function `pretty` is not part of the interface but just an alias for `prettyPrec Open`.

And, no, I'm not going to pester you with PRs every couple of minutes now. I have one final PR in the pipeline, which adds a couple of utility functions, but that should be it, then. :-)

### CODE REVIEW

**Comment by Z-snails** [comment]
Does the `PrettyPrec` interface not work for you?
I designed it to not hardcode idris's notion of precendence, which I think could come in useful.

**Comment by stefan-hoeck** [comment]
> Does the `PrettyPrec` interface not work for you? I designed it to not hardcode idris's notion of precendence, which I think could come in useful.

For me, it's not clear how to make use of it when deriving pretty printers for Idris data types using elab reflection. Should I just set `prec` to `Prec`? How does this benefit us in terms of flexibility, if `a` is a determining parameter anyway? Also, this means we typically need to implement two interfaces: `Pretty` and `PrettyPrec`. For instance: For `Pretty (List a)`, we just need `Pretty a`, but for `Pretty (Maybe a) Prec`, we'd need `PrettyPrec a Prec`. I just don't see how this should work in practice.

Have you used this in your own code with custom `prec`s? If yes, could you post an example, how you made use of it?

Still, if you decide on keeping it as it is right now, I think I can do with just using `PrettyPrec a Prec` and have a catch-all implementation for `Pretty`:

```idris
PrettyPrec a Prec => Pretty a where pretty = prettyPrec Open
```

**Comment by Z-snails** [comment]
No, I haven't a custom `Prec` myself.
The idea behind the determining parameter was that each data type needs a specific prec type.
And anyway, you can always write standalone functions if the interface isn't flexible enough.

**Comment by stefan-hoeck** [comment]
I'll close this then and go with what we have at the moment.

**Comment by stefan-hoeck** [comment]
Another question: Would it be acceptable, if we moved the interfaces to their own module? This would allow users of the library to import the pretty printer, without importing the interfaces as well.

**Comment by Z-snails** [comment]
Yeah sure, I wouldn't be too bothered if you removed them entirely if that would be easier.

Also I think there might have been a misunderstanding, I meant I'd be ok with your suggested changes and people who want extra flexibility can use standalone functions.
So if you want to reopen this, I'd be happy to merge these changes.

**Comment by stefan-hoeck** [comment]
In that case, I'll reopen this, because I think the interfaces are useful, and with this change they are similar to what we have now in contrib and idris2api.

**Comment by Z-snails** [comment]
I'd fix the conflicts myself but the web editor works so bad on mobile, but when they're resolved I'll merge it.

**Comment by stefan-hoeck** [comment]
I'm planning a final PR with some implementations for `Pretty`. Do you think we should split up the module or keep everything in a single file?

**Comment by Z-snails** [comment]
> I'm planning a final PR with some implementations for `Pretty`. Do you think we should split up the module or keep everything in a single file?

I think it would be good to split it up like this:

`Text.PrettyPrint.Bernardy.Core`: `Layout`, `Doc`, `render` etc.
`...Bernardy.Combinators`: stuff like `hsep`, `indent`
`...Bernardy.Interface`: `Pretty` and implementations
`...Bernardy`: reexports everything else

**Pull request merged**
